# MoveBase parameters
<%= namespace %>move_base:
  shutdown_costmaps: true
  controller_frequency: 5.0
  planner_frequency: 5.0
<%= namespace %>global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  static_map: true
<%= namespace %>local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false